using Meshes
using LinearAlgebra
using GeometryBasics

# coded by Mistral
function compute_cotangent_weight(a, b)
    # a and b are edge vectors meeting at a vertex
    # Returns cotangent of the angle between a and b
    cross_ab = cross(a, b)
    norm_cross = norm(cross_ab)
    if norm_cross < 1e-10
        return 0.0  # Parallel vectors
    end
    return dot(a, b) / norm_cross
end

# coded by Mistral
function compute_quad_laplacian(mm::SimpleMesh)

    n = nvertices(mm)
    L = spzeros(n, n)

    for (quad,top) in zip(mm, mm.topology)
        # Get the 4 vertices of the quadrangle
        v1, v2, v3, v4 = Vec3.(Tuple.(quad.vertices))
        i1,i2,i3,i4 = top.indices

        # Split the quadrangle into two triangles: v1-v2-v3 and v1-v3-v4
        # Triangle 1: v1, v2, v3
        e1 = v2 - v1
        e2 = v3 - v2
        e3 = v1 - v3
        w12 = compute_cotangent_weight(e1, -e2)  # Weight for edge v1-v2
        w23 = compute_cotangent_weight(e2, -e3)  # Weight for edge v2-v3
        w31 = compute_cotangent_weight(e3, -e1)  # Weight for edge v3-v1

        # Triangle 2: v1, v3, v4
        e4 = v4 - v3
        e5 = v1 - v4
        e6 = v3 - v1
        w34 = compute_cotangent_weight(e4, -e5)  # Weight for edge v3-v4
        w41 = compute_cotangent_weight(e5, -e6)  # Weight for edge v4-v1
        w13 = compute_cotangent_weight(e6, -e4)  # Weight for edge v1-v3

        # Update Laplacian entries for Triangle 1
        L[i1, i1] += w12 + w31
        L[i2, i2] += w12 + w23
        L[i3, i3] += w23 + w31
        L[i1, i2] -= w12
        L[i2, i1] -= w12
        L[i2, i3] -= w23
        L[i3, i2] -= w23
        L[i3, i1] -= w31
        L[i1, i3] -= w31

        # Update Laplacian entries for Triangle 2
        L[i1, i1] += w41 + w13
        L[i3, i3] += w34 + w13
        L[i4, i4] += w34 + w41
        L[i1, i3] -= w13
        L[i3, i1] -= w13
        L[i3, i4] -= w34
        L[i4, i3] -= w34
        L[i4, i1] -= w41
        L[i1, i4] -= w41
    end

    return L
end

# Modified slightly from Mistral generated code.
"""
    solve_harmonic_scalar_field(L, p1_index, p2_index)

Fit a harmonic potential `ϕ` using the beltrami-laplace matrix L with the constraints
that ϕ(p1_index) = 0 and ϕ(p2_index) = 1
"""
function solve_harmonic_scalar_field(L, p1_index, p2_index)
    n = size(L,1)
    # L: Laplacian matrix (n x n)
    # p1_index, p2_index: Indices of the constrained vertices
    # n: Number of vertices

    # Initialize the solution vector
    phi = zeros(n)

    # Separate free and constrained indices
    free_indices = setdiff(1:n, [p1_index, p2_index])
    constrained_indices = [p1_index, p2_index]

    # Extract submatrices
    L_ff = L[free_indices, free_indices]
    L_fc = L[free_indices, constrained_indices]

    # Boundary conditions: phi(p1) = 0, phi(p2) = 1
    phi_constrained = [0.0, 1.0]

    # Solve for free variables: L_ff * phi_f + L_fc * phi_constrained = 0
    phi_f = -L_ff \ (L_fc * phi_constrained)

    # Assign the solution
    phi[free_indices] = phi_f
    phi[p1_index] = 0.0
    phi[p2_index] = 1.0

    return phi
end

# Modified from code generated by Mistral
"""
"""
function compute_surface_gradient(phi, mm::SimpleMesh, L)
    vertices = mm.vertices
    n = length(vertices)
    grad_phi = Vector{Vec3}(undef, n)

    for i in 1:n
        grad = Vec3(0.0, 0.0, 0.0)
        for j in 1:n
            if L[i,j] != 0 && i != j
                # Compute cotangent weight for edge (i,j)
                w_ij = -L[i,j]

                # Unit vector from i to j
                e_ij = normalize(vertices[j] - vertices[i])

                # Contribution to the gradient
                grad += w_ij * (phi[j] - phi[i]) * e_ij
            end
        end
        grad_phi[i] = grad
    end

    return grad_phi
end

# Modified from code generated by Mistral
"""
    integrate_deformation_field(Tx::Vector{T}, mm, step_size=0.1, max_steps=100) where T <: GeometryBasics.Vec{N,T2} where T2 <: Real where N

Integrate the derformation field `Tx` defined on the mesh `mm` for `max_steps` steps of size `step_size`
"""
function integrate_deformation_field(Tx::Vector{T}, mm, step_size=0.1, max_steps=100) where T <: GeometryBasics.Vec{N,T2} where T2 <: Real where N
    # T: Deformation field (Vec3 per vertex)
    # vertices: Original vertex positions
    # quads: List of quad elements
    n = nelements(mm)
    new_idx = fill(0, n)
    cm = Point{N,Float64}.(Tuple.(centroid.(mm)))
    # For each vertex, integrate the deformation field to find its target
    for i in 1:n
        current_point = cm[i]
        current_T = Tx[i]
        closest_j = i
        for _ in 1:max_steps
            # Move in the direction of T
            new_point = current_point + step_size * current_T

            # Find the closest vertex to new_point
            distances = [norm(new_point - cm[j]) for j in 1:n]
            closest_j = argmin(distances)

            # Stop if we're not moving or we've reached a fixed point
            if norm(current_T) < 1e-6
                break
            end

            # Update for the next iteration
            #current_point = cm[closest_j]
            current_point = new_point
            current_T = Tx[closest_j]
        end
        new_idx[i] = closest_j
    end

    return new_idx 
end