name: Workflow for Codecov Hippocampus
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Julia 1.10.0
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.10.0"
      - run: julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/grero/NeuralCodingRegistry.jl.git"))'
        shell: bash
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}